# Generated by Django 3.1.5 on 2021-01-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text_input',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
