# Generated by Django 3.1.5 on 2021-01-08 15:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_reader', '0002_auto_20210108_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text_input',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
